[package]
name = "wz-publish-test"
version = "0.1.0"
edition = "2021"
description = "Test publish crate, don't use"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
